# Generated by Django 4.1.7 on 2023-02-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='fsdfsdf', upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.TextField(default='ewqe'),
            preserve_default=False,
        ),
    ]
